New version
Essent/nativescript-salesforce-dmp pull request #1
Opened 2018-04-17 09:24 UTC by dennis-montana

Created new plugin for Salesforce DMP

2018-04-17 10:37 UTC, bartsg commented on README.md
> +To use nativescript-ng-sentry you must first import the module:
Wrong plugin name?

2018-04-17 10:37 UTC, bartsg commented on README.md
> +SalesForce.getInstance().initialize('abcdefghij', true);
replace abcdefghij with YOUR_CONFIG_ID or something similar

2018-04-17 10:37 UTC, bartsg commented on demo/app/main-page.ts
> +    SalesForce.getInstance().initialize('abcdefghij', true);
Same here, would be more readable when replaced by YOUR_CONFIG_ID or so.

2018-04-17 10:50 UTC, bartsg approved these changes

2018-04-18 13:46 UTC, corne-de-bruin commented
First of all i would like to propose to rename this plugin to nativescript-salesforce-dmp because that really what's supported. Were not supporting the generic salesforce business

2018-04-18 13:50 UTC, corne-de-bruin requested changes
Again I would like to propose to rename all salesforce reference to salesforce-dmp

2018-04-19 08:29 UTC, martijnkooijman approved these changes

2018-04-19 10:30 UTC, merged